//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

//lots of namespaces to follow
using NSAIPlanner;
using NSWorldState;
using NSPlan;
using NSBlackBoard;
using NSActionStorage;
using NSGoalStorage;

namespace NSAgent
{
	public class Agent
	{
		AIPlanner		m_GoalPlanner;
		WorldState 		m_WorldState;
		Plan			m_Plan;
		BlackBoard		m_BlackBoard;
		ActionStorage	m_ActionStorage;
		GoalStorage		m_GoalStorage;

		public Agent()
		{
			Console.WriteLine ("Agent is being created");

			m_GoalPlanner 	= null;
			m_WorldState 	= null;
			m_Plan			= null;
			m_BlackBoard	= null;
			m_ActionStorage = null;
			m_GoalStorage 	= null;
		}

		~Agent()
		{
			Console.WriteLine ("Agent is being destroyed");

			m_GoalPlanner 	= null;
			m_WorldState 	= null;
			m_Plan			= null;
			m_BlackBoard	= null;
			m_ActionStorage = null;
			m_GoalStorage 	= null;
		}

		public void Init()
		{
            m_ActionStorage = new ActionStorage();
            m_GoalStorage = new GoalStorage(this);
            m_BlackBoard = new BlackBoard();
            m_WorldState = new WorldState();
            m_WorldState.ResetWS();
			m_GoalPlanner 	= new AIPlanner(this);
		
		}

		public AIPlanner GetGoalPlanner() { return m_GoalPlanner; }

		public WorldState GetWorldState() { return m_WorldState; }
		public void SetWorldState(WorldState worldstate) { m_WorldState = worldstate; }

		public Plan GetPlan() { return m_Plan; }
		public void SetPlan(Plan plan) { m_Plan = plan; }

		public ActionStorage GetActionStorage() { return m_ActionStorage; }

		public GoalStorage GetGoalStorage() { return m_GoalStorage; }

		public BlackBoard GetBlackBoard() { return m_BlackBoard;}

	
	}
}

